<?php
	//$wiki_path = "http://10.107.91.80/spoken_tutorial_org/index.php/";
	$wiki_path = "http://www.spoken-tutorial.org/wiki/index.php/";
	//$tutorial_path = "http://65.111.177.118/drupal6/sites/default/files/";
	$tutorial_path = "http://localhost/tester/sites/default/files/";
	$file_upload_path = '/var/www/tester/sites/default/files/';
	//$file_upload_path = '/var/www/tester/sites/default/files/';
?>
