<?php

function stupload_perm() {
	return array('Workshop Add New College');
}

function stupload_menu(){
	$items = array();
	
	$items['stupload/list'] = array(
		'page callback' => 'index',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['stupload/addfoss'] = array(
		'title' => 'Add New Foss Category',
		'description' => 'Add New Foss Category for ST Videos',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('add_foss_form'),
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'add_foss.inc',
	);
	$items['stupload/tutorial'] = array(
		'title' => 'Add New Tutorial Name',
		'description' => 'Add New Tutorial for Foss Category',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('add_tutorial_name_form'),
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'add_tutorial_name.inc',
	);
	$items['stupload/get_tutorial_levels'] = array(
		'page callback' => 'get_tutorial_levels',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['stupload/upload_english'] = array(
		'title' => 'Upload English',
		'description' => 'Upload English',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('upload_english_prerequest_form'),
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'upload_english_prerequest.inc',
	);
	$items['stupload/get_category_levels'] = array(
		'page callback' => 'get_category_levels',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['stupload/get_category_names'] = array(
		'page callback' => 'get_category_names',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['stupload/upload_english/outline'] = array(
		'title' => 'Upload English Outline',
		'description' => 'Upload English Outline',
		'page callback' => 'upload_english_outline',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'upload_english_outline.inc',
	);
	$items['stupload/upload_english/script'] = array(
		'title' => 'Upload English Script',
		'description' => 'Upload English Script',
		'page callback' => 'upload_english_script',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'upload_english_script.inc',
	);
	$items['stupload/upload_english/slide'] = array(
		'title' => 'Upload English Slide',
		'description' => 'Upload English Slide',
		'page callback' => 'upload_english_slide',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'upload_english_slide.inc',
	);
	$items['stupload/upload_english/video'] = array(
		'title' => 'Upload English Video',
		'description' => 'Upload English Video',
		'page callback' => 'upload_english_video',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'upload_english_video.inc',
	);
	$items['stupload/upload_english/codefile'] = array(
		'title' => 'Upload English Code',
		'description' => 'Upload English Code ',
		'page callback' => 'upload_english_codefile',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'upload_english_codefile.inc',
	);
	$items['stupload/upload_english/assignment'] = array(
		'title' => 'Upload English Assignment',
		'description' => 'Upload English Assignment ',
		'page callback' => 'upload_english_assignment',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'upload_english_assignment.inc',
	);

	// other languages
	$items['stupload/upload_other_lang'] = array(
		'title' => 'Upload Other Languages',
		'description' => 'Upload Other Languages',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('upload_other_lang_prerequest_form'),
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'upload_other_lang_prerequest.inc',
	);

	$items['stupload/get_languages'] = array(
		'page callback' => 'get_languages',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_NORMAL_ITEM,
	);

	$items['stupload/get_olang_tnames'] = array(
		'page callback' => 'get_olang_tnames',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_NORMAL_ITEM,
	);

	$items['stupload/upload_other_lang/outline'] = array(
		'page callback' => 'upload_olang_outline',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'upload_olang_outline.inc',
	);
	$items['stupload/upload_other_lang/script'] = array(

		'page callback' => 'upload_olang_script',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'upload_olang_script.inc',
	);
	$items['stupload/upload_other_lang/video'] = array(
		'page callback' => 'upload_olang_video',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'upload_olang_video.inc',
	);

  return $items;
}

// index page

function index(){

	$output = '<h2>Upload Options</h2>';
	$output .= "<div class='upload-index-page list-link'>";
	$output .= "<a class='addfoss' href='".$GLOBALS['base_path']."stupload/addfoss'> Add FOSS</a><br>";
	$output .= "<a class='tutorial' href='".$GLOBALS['base_path']."stupload/tutorial'> Add Tutorial Name</a><br>";
	$output .= "<a class='upload-english' href='".$GLOBALS['base_path']."stupload/upload_english'> Upload English</a><br>";
	$output .= "<a class='addfoss' href='".$GLOBALS['base_path']."stupload/addfoss'> Add FOSS</a>";
	//$output .= "<a class='addfoss' href='".$GLOBALS['base_path']."stupload/addfoss'> Add FOSS</a>";
	//$output .= "<a class='addfoss' href='".$GLOBALS['base_path']."stupload/addfoss'> Add FOSS</a>";
	//$output .= "<a class='addfoss' href='".$GLOBALS['base_path']."stupload/addfoss'> Add FOSS</a>";
	//$output .= "<a class='addfoss' href='".$GLOBALS['base_path']."stupload/addfoss'> Add FOSS</a>";
	$output .= "</div>";
	return $output;
}
// for add availabel tutorial levels for add tutorial names
function get_tutorial_levels(){
	if(isset($_POST['foss']) && !empty($_POST['level'])){
		$query = "select order_code from tutorial_details where foss_category='".$_POST['foss']."' and tutorial_level = '".$_POST['level']."'";
		//$query = "select order_code from tutorial_details where foss_category_id='6' and tutorial_level = 'D0'";
		$result = db_query($query);
		$exists_order = array();
		while($row = db_fetch_object($result)){
			$exists_order[] = $row->order_code;
		}
		
	}
	$i = 1;
	while($i < 100){
		$tutorial_order_no[] = $i;
		$i++;
	}
	$available = array_diff($tutorial_order_no, $exists_order);
	$send_data = array();
	foreach($available as $a){
		$send_data[] = $a;
	}
	echo json_encode($send_data);
	exit;
}
// getting tutorial level
function get_category_levels(){
	if(isset($_POST['foss'])){
		$query = "select distinct tutorial_level from tutorial_details where foss_category='".$_POST['foss']."'";
		$result = db_query($query);
		$output = array();
		while($row = db_fetch_object($result)){
			$output[] = $row;
			//$output[] = '2';
		}
		echo json_encode($output);
		exit;
	}
}

// getting tutorial names
function get_category_names(){
	if(isset($_POST['level']) && isset($_POST['foss'])){
		//$query = "select distinct tutorial_name from tutorial_details where tutorial_level='".$_POST['level']."'";

		$query = "SELECT  tutorial_name FROM tutorial_details WHERE foss_category='".$_POST['foss']."' and tutorial_level =  '".$_POST['level']."' AND tutorial_details.id NOT IN ( SELECT tutorial_detail_id FROM tutorial_resources)";
		$result = db_query($query);
		$output = array();
		while($row = db_fetch_object($result)){
			$output[] = $row;
		}
		echo json_encode($output);
		exit;
	}
}

// ******** for other languages ************
// getting other languages
// function get_languages(){
// 	if(isset($_POST['level']) && isset($_POST['foss'])){

// 		$query = "SELECT  tl.name FROM tutorial_languages tl WHERE  tl.name NOT IN ( SELECT language FROM tutorial_resources where tutorial_detail_id in (select id from tutorial_details where foss_category='".$_POST['foss']."' and tutorial_level='".$_POST['level']."'))";
// 		$result = db_query($query);
// 		$output = array();
// 		while($row = db_fetch_object($result)){
// 			$output[] = $row;
// 		}
// 		echo json_encode($output);
// 		exit;
// 	}
// }

// getting tutorial names
function get_olang_tnames(){
	if(isset($_POST['level']) && isset($_POST['foss']) && isset($_POST['lang'])){

		$query = "SELECT  tutorial_name FROM tutorial_details WHERE foss_category='".$_POST['foss']."' and tutorial_level =  '".$_POST['level']."' AND tutorial_details.id NOT IN ( SELECT tutorial_detail_id FROM tutorial_resources where language='".$_POST['lang']."')";
		$result = db_query($query);
		$output = array();
		while($row = db_fetch_object($result)){
			$output[] = $row;
		}
		echo json_encode($output);
		exit;
	}
}


?>
